schema:
  format:
    openapi: "3.0.0"
  environment_input_type: "PublicEnvironmentInput"
  types:
    PublicEnvironmentInput:
      type: object
      description: "Input properties for my environment"
      properties:
        pisicox:
          type: array
          items:
            type: string
            #default: ["subnet-077c40e6054c08d50", "subnet-0e98fbb9a66f9fe8c", "subnet-0b0234d390447f88d"]